version: '3.9'
services:
  cycling_db:
      image: postgres:latest
      container_name: local_db
      healthcheck:
        test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      restart: always
      environment: 
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=cycling
      ports:
        - 65432:5432
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
        - ./sql:/docker-entrypoint-initdb.d/